<?php

/**
 * @file
 * 
 * Includes hooks for the Leggodt module.
 */

/**
 * Implements hook_theme().
 */
function leggodt_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__leggodt_quotation' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_columns_even' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_columns_two_uneven' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_columns_three_uneven' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_heading' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_accordion' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_aside' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_call_to_action' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_carousel' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_hero' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_pull_quote' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_section' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_tabs' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_timeline' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_timeline_event' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_column_content' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_column_content_2' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_column_content_3' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_timeline_events' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_formatted_text' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_heading_text' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_image_field' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_quote' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_block_field' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_form_field' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_call_to_action_text' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_section_content' => [
      'base hook' => 'paragraph',
    ],
    'viewfield__paragraph__leggodt_view_field' => [
      'base hook' => 'paragraph',
    ],

  ];
}
