<?php

/**
 * Implements hook_theme().
 */
function leggodt_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__quotation' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__columns_even' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__columns_2_uneven' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__columns_3_uneven' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__heading' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_accordion' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_aside' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_call_to_action' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_hero' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_pull_quote' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_section' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__leggodt_tabs' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__timeline' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_column_content' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_column_content_2' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_column_content_3' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__leggodt_timeline_events' => [
      'base hook' => 'paragraph',
    ],

  ];
}
